// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: liteOS_Alpha

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Boot
void ui_Boot_screen_init(void);
void ui_event_Boot(lv_event_t * e);
lv_obj_t * ui_Boot;
lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t * ui_Home;
lv_obj_t * ui_MainMenu;
lv_obj_t * ui_MenuSelect;
lv_obj_t * ui_MenuSelect2;
// CUSTOM VARIABLES
lv_obj_t * uic_MainMenu;

// SCREEN: ui_Phone
void ui_Phone_screen_init(void);
lv_obj_t * ui_Phone;
lv_obj_t * ui_PhoneKeyboard;
lv_obj_t * ui_PhoneNumInput;
void ui_event_HomeBtn(lv_event_t * e);
lv_obj_t * ui_HomeBtn;
lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t * ui_Settings;
void ui_event_HomeBtn2(lv_event_t * e);
lv_obj_t * ui_HomeBtn2;
lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_Messages
void ui_Messages_screen_init(void);
lv_obj_t * ui_Messages;
void ui_event_HomeBtn3(lv_event_t * e);
lv_obj_t * ui_HomeBtn3;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_ActiveCall
void ui_ActiveCall_screen_init(void);
lv_obj_t * ui_ActiveCall;
lv_obj_t * ui_ActivePhoneNumber;
void ui_event_EndCall(lv_event_t * e);
lv_obj_t * ui_EndCall;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Boot(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 500, &ui_Home_screen_init);
    }
}

void ui_event_HomeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_HomeBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_HomeBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_EndCall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Home_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Boot_screen_init();
    ui_Home_screen_init();
    ui_Phone_screen_init();
    ui_Settings_screen_init();
    ui_Messages_screen_init();
    ui_ActiveCall_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Boot);
}
