// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: liteOS_Alpha

#include "ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMenu = lv_roller_create(ui_Home);
    lv_roller_set_options(ui_MainMenu, "Phone\nMessages\nSettings", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_MainMenu, 250);
    lv_obj_set_height(ui_MainMenu, 330);
    lv_obj_set_align(ui_MainMenu, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_MainMenu, lv_color_hex(0x4C4C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_MainMenu, &lv_font_montserrat_24, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainMenu, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainMenu, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_MenuSelect = lv_btn_create(ui_Home);
    lv_obj_set_width(ui_MenuSelect, 50);
    lv_obj_set_height(ui_MenuSelect, 71);
    lv_obj_set_x(ui_MenuSelect, 90);
    lv_obj_set_y(ui_MenuSelect, -2);
    lv_obj_set_align(ui_MenuSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuSelect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuSelect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuSelect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_MenuSelect, 270, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_MenuSelect, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_MenuSelect, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MenuSelect2 = lv_label_create(ui_MenuSelect);
    lv_obj_set_width(ui_MenuSelect2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuSelect2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuSelect2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuSelect2, ">");
    lv_obj_set_style_text_font(ui_MenuSelect2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_MainMenu = ui_MainMenu;

}
