// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: liteOS_Alpha

#include "ui.h"

void ui_IncomingCall_screen_init(void)
{
    ui_IncomingCall = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IncomingCall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IncomingCall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IncomingCall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_IncomingCall);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 93
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -132);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Incoming Call");

}
