// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: liteOS_Alpha

#include "ui.h"

void ui_Phone_screen_init(void)
{
    ui_Phone = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Phone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Phone, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Phone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PhoneKeyboard = lv_keyboard_create(ui_Phone);
    lv_keyboard_set_mode(ui_PhoneKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_PhoneKeyboard, 235);
    lv_obj_set_height(ui_PhoneKeyboard, 120);
    lv_obj_set_x(ui_PhoneKeyboard, 0);
    lv_obj_set_y(ui_PhoneKeyboard, 98);
    lv_obj_set_align(ui_PhoneKeyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PhoneKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PhoneKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PhoneKeyboard, lv_color_hex(0x212121), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PhoneKeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PhoneKeyboard, &lv_font_montserrat_18, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_PhoneNumInput = lv_textarea_create(ui_Phone);
    lv_obj_set_width(ui_PhoneNumInput, 225);
    lv_obj_set_height(ui_PhoneNumInput, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_PhoneNumInput, -9);
    lv_obj_set_y(ui_PhoneNumInput, -74);
    lv_obj_set_align(ui_PhoneNumInput, LV_ALIGN_CENTER);
    if("+-1234567890" == "") lv_textarea_set_accepted_chars(ui_PhoneNumInput, NULL);
    else lv_textarea_set_accepted_chars(ui_PhoneNumInput, "+-1234567890");
    lv_textarea_set_placeholder_text(ui_PhoneNumInput, "6035551234");
    lv_textarea_set_one_line(ui_PhoneNumInput, true);
    lv_obj_set_style_text_align(ui_PhoneNumInput, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PhoneNumInput, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PhoneNumInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PhoneNumInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PhoneNumInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PhoneNumInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_PhoneNumInput, LV_TEXT_ALIGN_CENTER, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_HomeBtn = lv_btn_create(ui_Phone);
    lv_obj_set_width(ui_HomeBtn, 50);
    lv_obj_set_height(ui_HomeBtn, 50);
    lv_obj_set_x(ui_HomeBtn, -91);
    lv_obj_set_y(ui_HomeBtn, -132);
    lv_obj_set_align(ui_HomeBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HomeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HomeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_HomeBtn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "<");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Phone);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 93
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 14
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -132);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Phone");

    lv_keyboard_set_textarea(ui_PhoneKeyboard, ui_PhoneNumInput);
    lv_obj_add_event_cb(ui_HomeBtn, ui_event_HomeBtn, LV_EVENT_ALL, NULL);

}
